#!/bin/bash
GREEN='\033[0;32m'

mkdir -p ~/work
cd ~/work

if [ -s `which brew` ]; then
    echo -e "${GREEN}brew はインストールされています"
else
    echo -e "${GREEN}brew をインストールしてください"
    exit
fi

if [ -s `which git` ]; then
    echo -e "${GREEN}git はインストールされています"
else
    echo -e "${GREEN}git をインストールします"
    brew install git
fi

git clone git@github.com:eguchi-ken/setup-mac 2>/dev/null
cd ~/work/setup-mac
git pull origin master

echo '\e[32m各パッケージ/アプリケーションをインストールします'
brew bundle -v

echo '\e[32m~/.bash_profile を置き換えます'
cat ~/work/setup-mac/bash_profile.sh  > ~/.bash_profile

cd ~/work


echo '\e[32memacs を設定します'
git clone git@github.com:eguchi-ken/dotemacs2.git 2>/dev/null
cd ~/work/dotemacs2/
git pull origin master
mkdir -p ~/.emacs.d/
ln -s init.el ~/.emacs.d/init.el

cd ~/work

echo '\e[32mrbenv を使って ruby2.5.5 をインストールします'
rbenv install 2.5.5
rbenv versions
